service: mynt-budget-tracker

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: ./.env.${opt:stage, 'dev'}
  allowedOrigins:
    dev: http://localhost:3000
    demo: https://mynt-demo.netlify.app # Update with your actual demo domain

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  logs:
    restApi:
      accessLogging: true
      executionLogging: true
      level: INFO
      fullExecutionData: true
  environment:
    PLAIDCLIENTID: ${env:PLAIDCLIENTID}
    PLAIDSECRET: ${env:PLAIDSECRET}
    PLAIDENV: ${env:PLAIDENV, 'sandbox'}
    USER_TABLE: ${self:service}-users-${self:provider.stage}
    TRANSACTIONS_TABLE: ${self:service}-transactions-${self:provider.stage}
    GOALS_TABLE: ${self:service}-goals-${self:provider.stage}
    USER_POOL_ID: !Ref CognitoUserPool
    USER_POOL_CLIENT_ID: !Ref CognitoUserPoolClient
    ALLOWED_ORIGINS: ${self:custom.allowedOrigins.${self:provider.stage}}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 
            - 'arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.USER_TABLE}'
            - 'arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.USER_TABLE}/index/*'
            - 'arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.GOALS_TABLE}'
            - 'arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.GOALS_TABLE}/index/*'
            - 'arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.TRANSACTIONS_TABLE}'
            - 'arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.TRANSACTIONS_TABLE}/index/*'
            - 'arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.NETWORTH_TABLE}'
            - 'arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.NETWORTH_TABLE}/index/*'
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
          Resource: 
            - 'arn:aws:logs:${self:provider.region}:${aws:accountId}:*'

functions:
  postConfirmation:
    handler: src/handlers/postConfirmation.handler
    events:
      - cognitoUserPool:
          pool: ${self:service}-user-pool-${opt:stage, 'dev'}
          trigger: PostConfirmation
          existing: true

  createLinkToken:
    handler: src/handlers/plaid.createLinkToken
    events:
      - http:
          path: /plaid/create-link-token
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
          authorizer:
            name: CognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn
  getUserInfo:
    handler: src/handlers/getUserInfo.handler
    events:
      - http:
          path: /getUserInfo
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
          authorizer:
            name: CognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn
  getAccountData:
    handler: src/handlers/account.getAccountData
    events:
      - http:
          path: /getAccountData
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
          authorizer:
            name: CognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn
  updateUserNetworth:
    handler: src/handlers/account.updateUserNetworth
    events:
      - http:
          path: /updateUserNetworth
          method: post
          cors:
            origin: '*'
            allowCredentials: false
          authorizer:
            name: CognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn
  exchangePublicToken:
    handler: src/handlers/plaid.exchangePublicToken
    events:
      - http:
          path: /plaid/exchange-token
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
          authorizer:
            name: CognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn
            claims:
              - email
              - sub
              - cognito:username
            resultTtlInSeconds: 0

  getTransactions:
    handler: src/handlers/plaid.getTransactions
    events:
      - http:
          path: /transactions
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
          authorizer:
            name: CognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn
            claims:
              - email
              - sub
              - cognito:username
            resultTtlInSeconds: 0
    timeout: 60

  signUp:
    handler: src/handlers/auth.signUp
    events:
      - http:
          path: /auth/signup
          method: post
          cors: true

  confirmSignUp:
    handler: src/handlers/auth.confirmSignUp
    events:
      - http:
          path: /auth/confirm
          method: post
          cors: true
  signIn:
    handler: src/handlers/auth.signIn
    events:
      - http:
          path: /auth/signin
          method: post
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USER_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        SSESpecification:
          SSEEnabled: true
    TransactionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TRANSACTIONS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: transactionId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:  
          - AttributeName: transactionId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: userId-index
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        SSESpecification:
          SSEEnabled: true
    NetworthTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.NETWORTH_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:  
          - AttributeName: userId
            KeyType: HASH
        SSESpecification:
          SSEEnabled: true
    GoalsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-goals-${opt:stage, 'dev'}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: goalId
            AttributeType: S
        KeySchema:
          - AttributeName: goalId
            KeyType: HASH
        SSESpecification:
          SSEEnabled: true

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-user-pool-${opt:stage, 'dev'}
        AutoVerifiedAttributes:
          - email
        UsernameAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId: !Ref CognitoUserPool
        ClientName: ${self:service}-user-pool-client-${self:provider.stage}
        GenerateSecret: false
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        SupportedIdentityProviders:
          - COGNITO
        CallbackURLs:
          - ${self:custom.allowedOrigins.${self:provider.stage}}/callback
        LogoutURLs:
          - ${self:custom.allowedOrigins.${self:provider.stage}}
        AllowedOAuthFlows:
          - code
        AllowedOAuthScopes:
          - email
          - openid
          - profile
        AllowedOAuthFlowsUserPoolClient: true

    CognitoUserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        Domain: mynt-budget-tracker-${opt:stage, 'dev'}-auth
        UserPoolId: !Ref CognitoUserPool

    ApiGatewayAccount:
      Type: AWS::ApiGateway::Account
      Properties:
        CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchLogsRole.Arn

    ApiGatewayCloudWatchLogsRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: apigateway.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'

outputs:
  UserPoolId:
    Value: !Ref CognitoUserPool
    Description: Cognito User Pool ID
  UserPoolClientId:
    Value: !Ref CognitoUserPoolClient
    Description: Cognito User Pool Client ID
  Region:
    Value: ${self:provider.region}
    Description: AWS Region
